# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto release CI

on:
  push:
    branches: [ release/rc ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - shell: bash
        run: git config --global user.email "dev+oss@tecsinapse.com.br" && git config --global user.name "Tecsinapse Release Bot"
      - name: New release
        run: mvn release:prepare release:perform -DskipTests -f pom.xml
        #git-release-bot-name: "Tecsinapse Release Bot"
        #git-release-bot-email: "dev+oss@tecsinapse.com.br"
